to: 4.19.0-ec.1
# 4.18 before 4.18.0-rc.4 OR 4.19.0-ec.0
from: 4[.](18[.]0-(ec[.].*|rc[.][0-3])|19[.]0-ec[.]0)
fixedIn: 4.19.0-ec.4
url: https://issues.redhat.com/browse/MCO-1585
name: LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO
message: Some clusters with some KubeletConfigs or ContainerRuntimeConfigs will have issues updating MachineConfigPools.
matchingRules:
- type: Always
