apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: graph-data
  namespace: openshift-update-service
spec:
  source:
    type: Git
    git:
      uri: https://github.com/openshift/cincinnati-graph-data.git
      ref: master
    dockerfile: |
      FROM registry.access.redhat.com/ubi8/ubi:8.1
      WORKDIR /home
      COPY . graph-data
      RUN mkdir -p /var/lib/cincinnati/graph-data
      CMD cp -rp graph-data/* /var/lib/cincinnati/graph-data
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: graph-data:latest
  triggers:
  - type: ConfigChange
